# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=sakura
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$$MYSQL_ROOT_USER", "-p$$MYSQL_ROOT_PASSWORD",  "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 1s
      retries: 16
      start_period: 30s
    volumes:
      - ../mysql/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ../mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - sakura

  hive:
    image: apache/hive:3.1.3
    container_name: hive
    depends_on:
      metastore:
        condition: service_started
    environment:
      - SERVICE_NAME=hiveserver2
      - IS_RESUME=true
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://metastore:9083
    ports:
      - 10000:10000
      - 10002:10002
    restart: unless-stopped
    networks:
      - sakura

  metastore:
    image: apache/hive:3.1.3
    container_name: metastore
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=mysql
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver -Djavax.jdo.option.ConnectionURL=jdbc:mysql://mysql:3306/hive_metastore?createDatabaseIfNotExist=true&useSSL=false -Djavax.jdo.option.ConnectionUserName=root -Djavax.jdo.option.ConnectionPassword=123456
    ports:
      - 9083:9083
    volumes:
      - ../hive/mysql-connector-j-8.2.0.jar:/opt/hive/lib/mysql.jar
    restart: unless-stopped
    networks:
      - sakura

networks:
  sakura:
    driver: bridge